version: '3.8'

services:
  backend-api:
    image: us-central1-docker.pkg.dev/specttra/specttra-deploy/specttra-api:v4
    container_name: api_service
    restart: unless-stopped
    volumes:
      - ./training_notebooks:/training_notebooks
      - ./specttra-api/app/models:/code/app/models 

    networks:
      - app-network

  frontend:
    image: us-central1-docker.pkg.dev/specttra/specttra-deploy/specttra-app:v7
    container_name: frontend_service
    restart: unless-stopped
    networks:
      - app-network

  nginx-proxy:
    image: nginx:stable-alpine
    container_name: reverse_proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend-api
      - frontend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge