version: '3.8'

services:
  backend-api:
    image: us-central1-docker.pkg.dev/specttra/specttra-deploy/specttra-api:latest
    container_name: api_service
    restart: unless-stopped

    # env_file:
    #   - ./.env
    networks:
      - app-network

  frontend:
    image: specttra-app:latest
    container_name: frontend_service
    restart: unless-stopped
    networks:
      - app-network

  nginx-proxy:
    image: nginx:stable-alpine
    container_name: reverse_proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443" # Uncomment this line when you are ready to configure SSL/HTTPS
    volumes:
      # It mounts our custom nginx configuration file
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      # - ./nginx/certs:/etc/nginx/certs:ro # Uncomment to mount SSL certificates
    depends_on:
      - backend-api
      - frontend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge